version: "3.0"
services:
   myapptest:
      build: ./
      container_name: test-app
      ports:
        - 3000:3000
      environment:
        - MONGOLAB_URI=mongodb://mongodb:27017/chat_dev
      depends_on:
        - mongodb       
      restart: on-failure  
   mongodb:
      image: mongo:3.6-xenial
      ports:
        - 27017:27017      
      environment:
        - MONGO_INITDB_DATABASE=chat_dev

